import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;          
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hafan
 */
public class FormTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form FormTransaksi
     */
   public FormTransaksi() {
    initComponents();
    load_table();

    // Non-editable untuk field hasil perhitungan
    txtJumlahBelanja.setEditable(false);
    txtDiskon.setEditable(false);
    txtBonus.setEditable(false);
    txtTotalBayar.setEditable(false);
}

    private void load_table() {
    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID Konsumen");
    model.addColumn("Nama Konsumen");
    model.addColumn("Alamat");
    model.addColumn("Nama Barang");
    model.addColumn("Harga");
    model.addColumn("Jumlah");
    model.addColumn("Jumlah Belanja");
    model.addColumn("Diskon");
    model.addColumn("Bonus");
    model.addColumn("Total Bayar");

    try {
        String sql = "SELECT * FROM swalayan";
        Connection conn = (Connection) Config.configDB();
        Statement stm = conn.createStatement();
        ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("id_konsumen"),
                res.getString("nama_konsumen"),
                res.getString("alamat"),
                res.getString("nama_barang"),
                res.getInt("harga"),
                res.getInt("jumlah"),
                res.getInt("jumlah_belanja"),
                res.getInt("diskon"),
                res.getString("bonus"),
                res.getInt("total_bayar")
            });
        }

        tblData.setModel(model);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "❌ Gagal memuat data:\n" + e.getMessage());
    }
}
    private void kosongkanForm() {
    txtIDKonsumen.setText("");
    txtNamaKonsumen.setText("");
    txtAlamat.setText("");
    txtNamaBarang.setText("");
    txtHarga.setText("");
    txtJumlahBeli.setText("");
    txtJumlahBelanja.setText("");
    txtDiskon.setText("");
    txtBonus.setText("");
    txtTotalBayar.setText("");
    groupDiskon.clearSelection(); // pastikan ada ButtonGroup
    txtIDKonsumen.requestFocus();  // cursor kembali ke atas
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupDiskon = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtIDKonsumen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaKonsumen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtJumlahBeli = new javax.swing.JTextField();
        txtJumlahBelanja = new javax.swing.JTextField();
        rbDapat = new javax.swing.JRadioButton();
        rbTidak = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtBonus = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotalBayar = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnBaru = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        txtIDKonsumen.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtIDKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDKonsumenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("ID KONSUMEN");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("NAMA KONSUMEN");

        txtNamaKonsumen.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("ALAMAT RUMAH");

        txtAlamat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("NAMA BARANG");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("HARGA SATUAN");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("JUMLAH BELI");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("JUMLAH BELANJA");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("DISKON");

        txtNamaBarang.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBarangActionPerformed(evt);
            }
        });

        txtHarga.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtJumlahBeli.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtJumlahBelanja.setBackground(new java.awt.Color(153, 255, 153));
        txtJumlahBelanja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtJumlahBelanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahBelanjaActionPerformed(evt);
            }
        });

        groupDiskon.add(rbDapat);
        rbDapat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbDapat.setText("DAPAT");
        rbDapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDapatActionPerformed(evt);
            }
        });

        groupDiskon.add(rbTidak);
        rbTidak.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbTidak.setText("TIDAK");
        rbTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTidakActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("BONUS");

        txtBonus.setBackground(new java.awt.Color(153, 255, 153));
        txtBonus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDiskon.setBackground(new java.awt.Color(153, 255, 153));
        txtDiskon.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiskonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("TOTAL PEMBAYARAN");

        txtTotalBayar.setBackground(new java.awt.Color(153, 255, 153));
        txtTotalBayar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnTambah.setBackground(new java.awt.Color(204, 204, 204));
        btnTambah.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(204, 204, 204));
        btnEdit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(204, 204, 204));
        btnHapus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCetak.setBackground(new java.awt.Color(204, 204, 204));
        btnCetak.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnBaru.setBackground(new java.awt.Color(204, 204, 204));
        btnBaru.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBaru.setText("BARU");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnSelesai.setBackground(new java.awt.Color(204, 204, 204));
        btnSelesai.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSelesai.setText("SELESAI");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblData.setGridColor(new java.awt.Color(0, 0, 0));
        tblData.setShowGrid(true);
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("TOKO SWAYALAN \"SAMI LARIZ\" SOLOKARTO");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("DATA KONSUMEN");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("TRANSAKSI PENJUALAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(317, 317, 317)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtIDKonsumen, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                                    .addComponent(txtAlamat))
                                                .addComponent(txtNamaKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnBaru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSelesai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbDapat)
                                                    .addComponent(rbTidak))))
                                        .addGap(83, 83, 83)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtJumlahBelanja, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addComponent(txtNamaBarang)
                                        .addComponent(txtHarga)
                                        .addComponent(txtJumlahBeli)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCetak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTambah, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(8, 8, 8))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnTambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNamaKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnHapus))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlahBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnCetak))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelesai)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbDapat)
                        .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbTidak)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDKonsumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKonsumenActionPerformed

    private void txtNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBarangActionPerformed

    private void txtJumlahBelanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahBelanjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahBelanjaActionPerformed

    private void rbDapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDapatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDapatActionPerformed

    private void txtDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiskonActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:                                        
    // VALIDASI INPUT WAJIB DIISI
    if (txtIDKonsumen.getText().isEmpty() ||
        txtNamaKonsumen.getText().isEmpty() ||
        txtAlamat.getText().isEmpty() ||
        txtNamaBarang.getText().isEmpty() ||
        txtHarga.getText().isEmpty() ||
        txtJumlahBeli.getText().isEmpty()) {

        JOptionPane.showMessageDialog(this, "❗ Semua field wajib diisi.", "Validasi", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // VALIDASI ANGKA UNTUK HARGA & JUMLAH BELI
    int harga, jumlah;
    try {
        harga = Integer.parseInt(txtHarga.getText());
        jumlah = Integer.parseInt(txtJumlahBeli.getText());

        if (harga < 0 || jumlah <= 0) {
            JOptionPane.showMessageDialog(this, "❗ Harga dan jumlah beli harus bernilai positif.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "❗ Harga dan jumlah beli harus berupa angka.", "Validasi", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // VALIDASI RADIO BUTTON DISKON
    if (!rbDapat.isSelected() && !rbTidak.isSelected()) {
        JOptionPane.showMessageDialog(this, "❗ Pilih apakah dapat diskon atau tidak.", "Validasi", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // HITUNG ARITMATIKA
    int jumlahBelanja = harga * jumlah;
    int diskon = rbDapat.isSelected() ? jumlahBelanja * 10 / 100 : 0;
    String bonus = jumlahBelanja >= 300000 ? "TAS CANTIK" : "VOUCHER";
    int total = jumlahBelanja - diskon;

    // TAMPILKAN KE FIELD OUTPUT
    txtJumlahBelanja.setText(String.valueOf(jumlahBelanja));
    txtDiskon.setText(String.valueOf(diskon));
    txtBonus.setText(bonus);
    txtTotalBayar.setText(String.valueOf(total));

    // SIMPAN KE DATABASE
    try {
        String sql = "INSERT INTO swalayan (id_konsumen, nama_konsumen, alamat, nama_barang, harga, jumlah, jumlah_belanja, diskon, bonus, total_bayar) VALUES "
                + "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        Connection conn = Config.configDB();
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, txtIDKonsumen.getText());
        pst.setString(2, txtNamaKonsumen.getText());
        pst.setString(3, txtAlamat.getText());
        pst.setString(4, txtNamaBarang.getText());
        pst.setInt(5, harga);
        pst.setInt(6, jumlah);
        pst.setInt(7, jumlahBelanja);
        pst.setInt(8, diskon);
        pst.setString(9, bonus);
        pst.setInt(10, total);

        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "✅ Data berhasil disimpan.");

        load_table();
        kosongkanForm();

    } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, "❌ Gagal menyimpan data:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
           kosongkanForm();
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:                                     
    try {
        String id = txtIDKonsumen.getText();

        // Pastikan field tidak kosong
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin dihapus dari tabel.");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Apakah kamu yakin ingin menghapus data dengan ID: " + id + "?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM swalayan WHERE id_konsumen=?";
            Connection conn = Config.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "✅ Data berhasil dihapus.");

            load_table();
            kosongkanForm();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Gagal menghapus data:\n" + e.getMessage());
    }

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:                                   
         try {
                String reportPath = "src/report/lapor_tokolariz.Jasper";

                HashMap<String, Object> parameters = new HashMap<>();
                Connection conn = Config.configDB(); // pastikan ini benar mengarah ke DB yang berisi data

                if (conn == null) {
                    throw new Exception("Koneksi database gagal.");
                }

                JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, conn);

                if (print.getPages().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Laporan tidak memiliki halaman. Cek isi data atau query-nya.");
                    return;
                }

                JasperViewer viewer = new JasperViewer(print, false);
                viewer.setExtendedState(JasperViewer.MAXIMIZED_BOTH);
                viewer.setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Gagal mencetak laporan: " + e.getMessage());
            }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
    int baris = tblData.rowAtPoint(evt.getPoint());

    txtIDKonsumen.setText(tblData.getValueAt(baris, 0).toString());
    txtNamaKonsumen.setText(tblData.getValueAt(baris, 1).toString());
    txtAlamat.setText(tblData.getValueAt(baris, 2).toString());
    txtNamaBarang.setText(tblData.getValueAt(baris, 3).toString());
    txtHarga.setText(tblData.getValueAt(baris, 4).toString());
    txtJumlahBeli.setText(tblData.getValueAt(baris, 5).toString());
    txtJumlahBelanja.setText(tblData.getValueAt(baris, 6).toString());
    txtDiskon.setText(tblData.getValueAt(baris, 7).toString());
    txtBonus.setText(tblData.getValueAt(baris, 8).toString());
    txtTotalBayar.setText(tblData.getValueAt(baris, 9).toString());

    // Opsional: pilih radio button sesuai diskon
    if (!txtDiskon.getText().equals("0")) {
        rbDapat.setSelected(true);
    } else {
        rbTidak.setSelected(true);
    }

    }//GEN-LAST:event_tblDataMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:                                  
    try {
        String sql = "UPDATE swalayan SET "
                + "nama_konsumen=?, "
                + "alamat=?, "
                + "nama_barang=?, "
                + "harga=?, "
                + "jumlah=?, "
                + "jumlah_belanja=?, "
                + "diskon=?, "
                + "bonus=?, "
                + "total_bayar=? "
                + "WHERE id_konsumen=?";

        Connection conn = Config.configDB();
        PreparedStatement pst = conn.prepareStatement(sql);

        int harga = Integer.parseInt(txtHarga.getText());
        int jumlah = Integer.parseInt(txtJumlahBeli.getText());
        int jumlahBelanja = harga * jumlah;
        int diskon = rbDapat.isSelected() ? jumlahBelanja * 10 / 100 : 0;
        String bonus = jumlahBelanja >= 300000 ? "TAS CANTIK" : "VOUCHER";
        int total = jumlahBelanja - diskon;

        // Isi statement SQL
        pst.setString(1, txtNamaKonsumen.getText());
        pst.setString(2, txtAlamat.getText());
        pst.setString(3, txtNamaBarang.getText());
        pst.setInt(4, harga);
        pst.setInt(5, jumlah);
        pst.setInt(6, jumlahBelanja);
        pst.setInt(7, diskon);
        pst.setString(8, bonus);
        pst.setInt(9, total);
        pst.setString(10, txtIDKonsumen.getText());

        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "✅ Data berhasil diubah.");

        load_table();
        kosongkanForm();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Gagal edit data:\n" + e.getMessage());
    }

    }//GEN-LAST:event_btnEditActionPerformed

    private void rbTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTidakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTidakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnTambah;
    private javax.swing.ButtonGroup groupDiskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbDapat;
    private javax.swing.JRadioButton rbTidak;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIDKonsumen;
    private javax.swing.JTextField txtJumlahBelanja;
    private javax.swing.JTextField txtJumlahBeli;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtNamaKonsumen;
    private javax.swing.JTextField txtTotalBayar;
    // End of variables declaration//GEN-END:variables


}
